### ISSUE TITLE
main does not build with clang 21.1.8 under GCS_WERROR: two warnings CI does not see

### ISSUE THREAD

**Issue by ciaranm** [ciaranm/glasgow-constraint-solver#759]
`main` (`d04983f9`) does not build with clang 21.1.8 under `-DGCS_WERROR=ON`, in two places, both of which the `ubuntu-26.04 (clang++)` CI lane is currently happy with:

```
gcs/variable_weighting.hh:134:22: error: 'on_restart' overrides a member function but is
    not marked 'override' [-Werror,-Winconsistent-missing-override]

gcs/constraints/element/element.cc:330:17: error: lambda capture 'array_has_nonconstants'
    is not used [-Werror,-Wunused-lambda-capture]
gcs/constraints/element/element.cc:466:17: (same)
gcs/constraints/element/element.cc:578:17: (same)
```

Both are trivial: an `override` keyword, and three captures that are genuinely unused (`array_has_nonconstants` is captured by three propagator lambdas and referenced by none of them — worth a glance at whether the *guard* it was meant to be is missing, rather than only deleting the capture).

Neither is caught by CI, so the local toolchain is now ahead of the runner's. That is worth knowing on its own: **a red local clang build is currently not evidence against the branch under test**, which cost time on #758 before it was traced back to `main`. The workaround while it stands is to syntax-check only the changed files, pulling their commands out of `compile_commands.json` and adding `-Wno-inconsistent-missing-override -Wno-unused-lambda-capture` — note that `-DCMAKE_CXX_FLAGS=...` on the configure line does not reach the compile line here, for the same reason `CMAKE_CXX_FLAGS_SANITIZE` did not in #597.

Low priority, but cheap, and the `element.cc` one may be hiding a dropped condition.

**Comment by ciaranm** [comment]
Closing: both halves are dealt with on `main` (238c7836).

- `VariableWeighting::on_restart()` now says `override`.
- The three unused-capture warnings in `element.cc` are kept on purpose, and no guard is missing. Each propagator reads `array_has_nonconstants` only in a branch that an `if constexpr` discards for a constant array. So clang reports the capture as unused in that instantiation, while the variable-array instantiation needs it: deleting the captures was tried, and it breaks that build.

The comment beside `GCS_WERROR` in `CMakeLists.txt` records this, and records that a clang `-Werror` lane would need `-Wno-unused-lambda-capture`. So a local clang 21 `-Werror` build still stops on those three lines, by design.

---
Closed by an AI agent (Claude) during an issue-housekeeping pass, checked against `main` at `e0bc7039`.
