### PR TITLE
Cpp23ification round two

### PR DESCRIPTION
**Pull request by ciaranm**
Needs tidying up, but will this at least compile everywhere we care about?

### CODE REVIEW

**Comment by ciaranm** [comment]
@mmcilree @philrod1 Can you try this on your preferred platform, and see if it still compiles? If it works I'll get Claude to tidy it up (for science...) and merge in a clean version.

**Comment by mmcilree** [comment]
> @mmcilree @philrod1 Can you try this on your preferred platform, and see if it still compiles? If it works I'll get Claude to tidy it up (for science...) and merge in a clean version.

I get a failure with homebrew-installed clang 21.1.8
```
[207/246] Linking CXX executable solve_test
FAILED: [code=1] solve_test
: && /opt/homebrew/Cellar/llvm/21.1.8/bin/clang++ -arch arm64 -Wl,-search_paths_first -Wl,-headerpad_max_install_names -pthread gcs/CMakeFiles/solve_test.dir/solve_test.cc.o -o solve_test  gcs/libglasgow_constraint_solver.a  _deps/catch2-build/src/libCatch2Main.a  _deps/catch2-build/src/libCatch2.a && :
Undefined symbols for architecture arm64:
  "std::__1::__hash_memory(void const*, unsigned long)", referenced from:
      std::__1::pair<std::__1::__hash_iterator<std::__1::__hash_node<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, void*>*>, bool> std::__1::__hash_table<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>::__emplace_unique_key_args<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in libglasgow_constraint_solver.a[6](problem.cc.o)
ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
[216/246] Building CXX object minizinc/CMakeFiles/fzn-glasgow.dir/fzn_glasgow.cc.o
ninja: build stopped: subcommand failed.
```
Apple clang-17 and g++-15 both work fine though.

**Comment by philrod1** [comment]
It's working fine in an Ubuntu 26.04 VM.
cpp (Ubuntu 15.2.0-16ubuntu1) 15.2.0

**Comment by ciaranm** [comment]
@mmcilree that looks like it might be related to how you have clang / libc++ installed? https://github.com/Homebrew/homebrew-core/issues/235411 and https://github.com/llvm/llvm-project/pull/140072 might have fixes: does updating brew and then reinstalling clang and libc++ fix it?

**Comment by mmcilree** [comment]
> @mmcilree that looks like it might be related to how you have clang / libc++ installed? [Homebrew/homebrew-core#235411](https://github.com/Homebrew/homebrew-core/issues/235411) and [llvm/llvm-project#140072](https://github.com/llvm/llvm-project/pull/140072) might have fixes: does updating brew and then reinstalling clang and libc++ fix it?

Okay yes I can confirm `brew install llvm@21` fixes the issue.

**Review by philrod1 — APPROVED** [review]
Quite the few changes, there.  LGTM

**Comment by ciaranm** [comment]
Assuming the checks pass, I'm going to merge this. If you want me to go and fix your other branches based upon these changes, I can do it pretty quickly.

**Comment by philrod1** [comment]
If you like, or I could do it tomorrow.

**Comment by ciaranm** [comment]
I'll leave it to you unless you run into anything unobvious.
